lib/ioquiz_web/router.ex
defmodule IoquizWeb.Router do
  use IoquizWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug IoquizWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IoquizWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", IoquizWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/lessons", LessonController do
      resources "/questions", QuestionController, except: [:index] do
        resources "/components", ComponentController, except: [:index]
      end
    end

    resources "/student_quizzes", StudentQuizController
  end

  # Other scopes may use custom stacks.
  # scope "/api", IoquizWeb do
  #   pipe_through :api
  # end
end

lib/ioquiz/quiz/lesson.ex
defmodule Ioquiz.Quiz.Lesson do
  use Ecto.Schema
  import Ecto.Changeset


  schema "lessons" do
    field :information, :string
    field :title, :string

    belongs_to :user, Ioquiz.Accounts.User
    has_many :questions, Ioquiz.Quiz.Question

    timestamps()
  end

  @doc false
  def changeset(lesson, attrs) do
    lesson
    |> cast(attrs, [:title, :information])
    |> validate_required([:title, :information])
  end
end

lib/ioquiz_web/controllers/lesson_controller.ex
defmodule IoquizWeb.LessonController do
  use IoquizWeb, :controller

  alias Ioquiz.Quiz
  alias Ioquiz.Quiz.Lesson

  def index(conn, _params, current_user) do
    lessons = Quiz.list_user_lessons(current_user)
    render(conn, "index.html", lessons: lessons)
  end

  def new(conn, _params, current_user) do
    changeset = Quiz.change_lesson(current_user, %Lesson{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"lesson" => lesson_params}, current_user) do
    case Quiz.create_lesson(current_user, lesson_params) do
      {:ok, lesson} ->
        conn
        |> put_flash(:info, "Lesson created successfully.")
        |> redirect(to: Routes.lesson_path(conn, :show, lesson))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, current_user) do
    lesson = Quiz.get_user_lesson!(current_user, id)
    render(conn, "show.html", lesson: lesson)
  end

  def edit(conn, %{"id" => id}, current_user) do
    lesson = Quiz.get_user_lesson!(current_user, id)
    changeset = Quiz.change_lesson(current_user, lesson)
    render(conn, "edit.html", lesson: lesson, changeset: changeset)
  end

  def update(conn, %{"id" => id, "lesson" => lesson_params}, current_user) do
    lesson = Quiz.get_user_lesson!(current_user, id)

    case Quiz.update_lesson(lesson, lesson_params) do
      {:ok, lesson} ->
        conn
        |> put_flash(:info, "Lesson updated successfully.")
        |> redirect(to: Routes.lesson_path(conn, :show, lesson))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", lesson: lesson, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, current_user) do
    lesson = Quiz.get_user_lesson!(current_user, id)
    {:ok, _lesson} = Quiz.delete_lesson(lesson)

    conn
    |> put_flash(:info, "Lesson deleted successfully.")
    |> redirect(to: Routes.lesson_path(conn, :index))
  end


  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end
end

lib/ioquiz_web/views/lesson_view.ex
defmodule IoquizWeb.LessonView do
  use IoquizWeb, :view
end

lib/ioquiz_web/templates/lesson/edit.html.eex
<h1>Edit Lesson</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.lesson_path(@conn, :update, @lesson)) %>

<span><%= link "Back", to: Routes.lesson_path(@conn, :show, @lesson) %></span>

lib/ioquiz_web/templates/lesson/form.html.eex
<%= form_for @changeset, @action, [class: "uk-form-stacked"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="uk-alert-danger" uk-alert>
      <a class="uk-alert-close" uk-close></a>
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="uk-margin">
    <%= label f, :title, class: "uk-form-label" %>
    <div class="uk-form-controls">
      <%= text_input f, :title, class: "uk-input" %>
    </div>
    <%= error_tag f, :title %>
  </div>

  <div class="uk-margin">
    <%= label f, :information, class: "uk-form-label" %>
    <div class="uk-form-controls">
      <%= textarea f, :information, class: "uk-textarea" %>
    </div>
    <%= error_tag f, :information %>
  </div>

  <div class="uk-margin">
    <%= submit "Save", class: "uk-button uk-button-primary" %>
  </div>
<% end %>

lib/ioquiz_web/templates/lesson/index.html.eex
<h1>Quizzes</h1>

<table class="uk-table">
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for lesson <- @lessons do %>
    <tr>
      <td><%= lesson.title %></td>

      <td>
        <%= link "Show", to: Routes.lesson_path(@conn, :show, lesson) %>
        |
        <%= link "Delete", to: Routes.lesson_path(@conn, :delete, lesson), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link "New Quiz", to: Routes.lesson_path(@conn, :new), class: "uk-button uk-button-primary" %>

lib/ioquiz_web/templates/lesson/new.html.eex
<h1>New Lesson</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.lesson_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.lesson_path(@conn, :index) %></span>

lib/ioquiz_web/templates/lesson/show.html.eex
<h1><%= @lesson.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @lesson.information %>
</p>

<%= link "Edit", to: Routes.lesson_path(@conn, :edit, @lesson), class: "uk-button uk-button-default uk-button-small" %>&nbsp;
<%= link "Back", to: Routes.lesson_path(@conn, :index), class: "uk-button uk-button-default uk-button-small" %>

<h2>Questions</h2>

<%= link "New Question", to: Routes.lesson_question_path(@conn, :new, @lesson), class: "uk-button uk-button-primary" %>

<ol>
<%= for question <- @lesson.questions do %>
  <li>
    <%= question.question %>
    <%= link "Show", to: Routes.lesson_question_path(@conn, :show, @lesson, question) %>
    |
    <%= link "Delete", to: Routes.lesson_question_path(@conn, :delete, @lesson, question), method: :delete, data: [confirm: "Are you sure?"] %>
  </li>
<% end %>
</ol>

<%= link "New Question", to: Routes.lesson_question_path(@conn, :new, @lesson), class: "uk-button uk-button-primary" %>