lib/ioquiz_web/router.ex
defmodule IoquizWeb.Router do
  use IoquizWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug IoquizWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IoquizWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", IoquizWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/lessons", LessonController do
      resources "/questions", QuestionController, except: [:index] do
        resources "/components", ComponentController, except: [:index]
      end
    end

    resources "/student_quizzes", StudentQuizController
  end

  # Other scopes may use custom stacks.
  # scope "/api", IoquizWeb do
  #   pipe_through :api
  # end
end

lib/ioquiz_web/views/layout_view.ex
defmodule IoquizWeb.LayoutView do
  use IoquizWeb, :view
end

lib/ioquiz_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Ioquiz · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <div class="uk-navbar-container uk-margin" uk-navbar>
        <div class="uk-navbar-left">
          <a href="/" class="uk-navbar-item uk-logo">IOQuiz</a>
          <ul class="uk-navbar-nav">
            <li><%= link "Users", to: Routes.user_path(@conn, :index), class: "navbar-item" %></li>
              <li><%= link "Quizzes", to: Routes.lesson_path(@conn, :index), class: "navbar-item" %></li>
          </ul>
        </div>
        <div class="uk-navbar-right">
          <%= if @current_user do %>
            <div class="uk-navbar-item"><%= @current_user.name %></div>
          <% end %>
          <ul class="uk-navbar-nav">
            <%= if @current_user do %>
              <li><%= link "Log Out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete" %>
            <% else %>
              <li><%= link "Register", to: Routes.user_path(@conn, :new) %>
              <li><%= link "Log In", to: Routes.session_path(@conn, :new) %>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <main role="main" class="uk-container">
      <%= if get_flash(@conn, :info) do %>
        <div class="uk-alert-success" uk-alert>
          <a class="uk-alert-close" uk-close></a>
          <p><%= get_flash(@conn, :info) %></p>
        </div>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <div class="uk-alert-danger" uk-alert>
          <a class="uk-alert-close" uk-close></a>
          <p><%= get_flash(@conn, :error) %></p>
        </div>
      <% end %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.5/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.5/js/uikit-icons.min.js"></script>
  </body>
</html>