lib/ioquiz_web/router.ex
defmodule IoquizWeb.Router do
  use IoquizWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug IoquizWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IoquizWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", IoquizWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/lessons", LessonController do
      resources "/questions", QuestionController, except: [:index] do
        resources "/components", ComponentController, except: [:index]
      end
    end

    resources "/student_quizzes", StudentQuizController
  end

  # Other scopes may use custom stacks.
  # scope "/api", IoquizWeb do
  #   pipe_through :api
  # end
end

lib/ioquiz/quiz/question.ex
defmodule Ioquiz.Quiz.Question do
  use Ecto.Schema
  import Ecto.Changeset


  schema "questions" do
    field :question, :string
    belongs_to :lesson, Ioquiz.Quiz.Lesson
    has_many :components, Ioquiz.Quiz.Component

    timestamps()
  end

  @doc false
  def changeset(question, attrs) do
    question
    |> cast(attrs, [:question, :lesson_id])
    |> validate_required([:question])
  end
end

lib/ioquiz_web/controllers/question_controller.ex
defmodule IoquizWeb.QuestionController do
  use IoquizWeb, :controller

  alias Ioquiz.Quiz
  alias Ioquiz.Quiz.Question

  def new(conn, _params, lesson) do
    changeset = Quiz.change_question(lesson, %Question{})
    render(conn, "new.html", changeset: changeset, lesson: lesson)
  end

  def create(conn, %{"question" => question_params}, lesson) do
    case Quiz.create_question(lesson, question_params) do
      {:ok, question} ->
        conn
        |> put_flash(:info, "Question created successfully.")
        |> redirect(to: Routes.lesson_question_path(conn, :show, lesson, question))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, lesson: lesson)
    end
  end

  def show(conn, %{"id" => id}, lesson) do
    question = Quiz.get_lesson_question!(lesson, id)
    IO.inspect question
    render(conn, "show.html", lesson: lesson, question: question)
  end

  def edit(conn, %{"id" => id}, lesson) do
    question = Quiz.get_lesson_question!(lesson, id)
    changeset = Quiz.change_question(lesson, question)
    render(conn, "edit.html", lesson: lesson, question: question, changeset: changeset)
  end

  def update(conn, %{"id" => id, "question" => question_params}, lesson) do
    question = Quiz.get_lesson_question!(lesson, id)

    case Quiz.update_question(question, question_params) do
      {:ok, question} ->
        conn
        |> put_flash(:info, "Question updated successfully.")
        |> redirect(to: Routes.lesson_question_path(conn, :show, lesson, question))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", lesson: lesson, question: question, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, lesson) do
    question = Quiz.get_lesson_question!(lesson, id)
    {:ok, _question} = Quiz.delete_question(question)

    conn
    |> put_flash(:info, "Question deleted successfully.")
    |> redirect(to: Routes.lesson_path(conn, :show, lesson))
  end

  def action(conn, _) do
    lesson = Quiz.get_lesson!(conn.params["lesson_id"])
    args = [conn, conn.params, lesson]
    apply(__MODULE__, action_name(conn), args)
  end
end

lib/ioquiz_web/views/question_view.ex
defmodule IoquizWeb.QuestionView do
  use IoquizWeb, :view
end

lib/ioquiz_web/templates/question/edit.html.eex
<h1>Edit Question</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.lesson_question_path(@conn, :update, @lesson, @question)) %>

<span><%= link "Back", to: Routes.lesson_question_path(@conn, :show, @lesson, @question) %></span>

lib/ioquiz_web/templates/question/form.html.eex
<%= form_for @changeset, @action, [class: "uk-form-stacked"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="uk-alert-danger" uk-alert>
      <a class="uk-alert-close" uk-close></a>
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="uk-margin">
    <%= label f, :question, class: "uk-form-label" %>
    <div class="uk-form-controls">
      <%= textarea f, :question, class: "uk-textarea" %>
    </div>
    <%= error_tag f, :question %>
  </div>

  <div class="uk-margin">
    <%= submit "Save", class: "uk-button uk-button-primary" %>
  </div>
<% end %>

lib/ioquiz_web/templates/question/new.html.eex
<h1>New Question</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.lesson_question_path(@conn, :create, @lesson)) %>

<span><%= link "Back", to: Routes.lesson_path(@conn, :show, @lesson) %></span>

lib/ioquiz_web/templates/question/show.html.eex
<h1><%= @lesson.title %></h1>
<h3>Question:</h3>
<div class="uk-text-large uk-margin"><%= @question.question %></div>

<%= link "Edit", to: Routes.lesson_question_path(@conn, :edit, @lesson, @question), class: "uk-button uk-button-default uk-button-small" %>&nbsp;
<%= link "Back", to: Routes.lesson_path(@conn, :show, @lesson), class: "uk-button uk-button-default uk-button-small" %>

<h3>Items:</h3>

<table class="uk-table">
  <thead>
    <tr>
      <th>Content</th>
      <th>Type</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
      <%= for component <- @question.components do %>
          <tr>
            <td><%= component.content %></td>
            <td><%= component.type %></td>

            <td>
              <%= link "Edit", to: Routes.lesson_question_component_path(@conn, :edit, @lesson, @question, component) %>
              |
              <%= link "Delete", to: Routes.lesson_question_component_path(@conn, :delete, @lesson, @question, component), method: :delete, data: [confirm: "Are you sure?"] %>
            </td>
          </tr>
      <% end %>
  </tbody>
</table>

<%= link "New Item", to: Routes.lesson_question_component_path(@conn, :new, @lesson, @question), class: "uk-button uk-button-primary" %>